name: Workflow

#Trigger
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "This is my runner"
      - name : list files
        run: ls
      - name: Read files
        run: cat README.md

