name: Workflow

#Trigger
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4.2.2

            - name: List Repo files
              run: ls -ltra
            
            - name: Executing shell script
              run: ./ascii-script.sh
