name: Workflow

#Trigger
on: push
jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4.2.2

            - name: Install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Sleep for 30 seconds
              run: sleep 30
    
    test_job1:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
            - name: checkout repo
              run: sleep 10
    test_job2:
        runs-on: ubuntu-latest
        needs: [test_job1]
        steps:
            - name: listing the directory
              run: ls

              


